### ISSUE TITLE
Minor FR: URI to update current Theme

### ISSUE THREAD

**Issue by chrisgrieser** [Vinzent03/obsidian-advanced-uri#34]
Analogue to the URI to update plugins, there could also be an URI to update the currently used theme.

**Comment by Vinzent03** [comment]
I don't want to break anything, so I only want to click on the existing buttons. (A part of updating is handled in the button onClick function, which I cannot really call without pressing the button). In addition, I don't know how to find the proper button, because there are several buttons. All in all, I don't think I will add this feature. I mean, how often do you update your theme? I think once a week is enough. And I doubt that a URI is necessary.

**Comment by chrisgrieser** [comment]
Ah, I see, you are simulating button presses.

Well I was thinking about simply unifying the updates of plugins and theme. But its really not a necessary feature, indeed. Thanks for the explanation and all the other super quick updates!
