### ISSUE TITLE
Support copying links to workspaces

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-advanced-uri#42]
Currently, there are options for copying links to files, commands, etc. It would be great if there can be a command for copying links to workspaces.

**Comment by julroger2013** [comment]
+1 on this one

Could probably do this with Templater, somehow, mapping a script as a command that you can call up with Advanced URI, but would be nice just to have Copy Workspace Link as an built-in command.

**Comment by julroger2013** [comment]
The copy workspace link command is awesome. I'm really enjoying it.

I wonder, however, if it would be possible to add a "copy link to current workspace" command?

For context: My use case would be adding this command to an in-note toolbar with the Note Toolbars plugin. I have dedicated workspaces for various writing projects, and I would love to have a one-click option to grab a link to the currently open workspace that I can then paste in my task manager or otherwise.

Thanks for adding a workspace link command!

**Comment by Vinzent03** [comment]
I think a dedicated uri endpoint to copy an uri for the current workspace is a better fit than an Obsidian command, which you would call with an uri either way, right? What do you think?

**Comment by julroger2013** [comment]
I don't quite know what you mean by a dedicated URI endpoint. I'm sorry that I'm not understanding.

My hope was to use the Note Toolbar plugin to add a button in my notes that would copy the link to the current workspace. Any option that makes copying the workspace link with a single click would be perfect for what I'm envisioning. Would a URI endpoint make that possible?

**Comment by Vinzent03** [comment]
It's now available in v1.43.0 :tada: Instead of a command use an URI for the Note Toolbars plugin. Construct the URI with any value for the `workspace` parameter and add `clipboard=true` as parameter. When called, you get an URI for the current workspace copied to your clipboard. Documentation: https://publish.obsidian.md/advanced-uri-doc/Actions/Navigation

**Comment by julroger2013** [comment]
Thanks so much! That's perfect for my purposes.
