### ISSUE TITLE
Fails to append - Shortcuts + Siri + Daily Note

### ISSUE THREAD

**Issue by mfloreen** [Vinzent03/obsidian-advanced-uri#60]
I've made a simple workflow in Shortcuts for iOS so that I can log a podcast, with notes, to my Daily Note in Obsidian (see screenshots below). I have two steps using Advanced URI, one to open Obsidian and create a daily note, and another to append to it.

Now, when I run this from the Shortcuts app, it works as expected. But when I run it with Siri (i.e. while driving), the second Advanced URI step does not actually write anything to Obsidian. I don't have much coding experience, but I've tried everything I can think of to get this to work. It still consistently fails to actually append my text. 

![IMG_2840](https://user-images.githubusercontent.com/6507971/178097411-39e14318-a699-46ef-b97b-6bc194e807e5.PNG)
![IMG_2841](https://user-images.githubusercontent.com/6507971/178097364-27404591-efdb-47e0-9f14-76ad2d67bb8f.PNG)

**Comment by Vinzent03** [comment]
I don't know what changes when you execute the shortcut via Siri. Could you try running only the second command? So without creating the daily note in another step before. I think it should still work.

**Comment by FelipeRearden** [comment]
Let me try to help @mfloreen ...

> But when I run it with Siri (i.e. while driving), the second Advanced URI step does not actually write anything to Obsidian.

Some ideas 💡💡💡

1️⃣ **Try to Add some WAIT action in the shortcut**

I think the Shortcut is running faster than Obsidian. Try to add WAIT 5 seconds to give time to open Obsidian and after this, run the last URI.

2️⃣ **Add the Command Focus on Editor to your Shortcut before the last URI**

Sometimes the second URI is not been append/prepend because there is no active note. The note is open but it is not the active note. 

Use a URI to run this command in your Shortcut

---

I hope you get what you want 🙏
